services:
  zabbix-db:
    image: postgres:15
    container_name: zabbix-db
    environment:
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix_password
      POSTGRES_DB: zabbix
    volumes:
      - zabbix-db-data:/var/lib/postgresql/data
    networks:
      - zabbix-network
    restart: unless-stopped

  zabbix-server:
    image: zabbix/zabbix-server-pgsql:latest
    container_name: zabbix-server
    environment:
      DB_SERVER_HOST: zabbix-db
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix_password
      POSTGRES_DB: zabbix
    depends_on:
      - zabbix-db
    volumes:
      - zabbix-server-data:/var/lib/zabbix
    ports:
      - "10051:10051"
    networks:
      - zabbix-network
    restart: unless-stopped

  zabbix-web:
    image: zabbix/zabbix-web-nginx-pgsql:latest
    container_name: zabbix-web
    environment:
      DB_SERVER_HOST: zabbix-db
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix_password
      POSTGRES_DB: zabbix
      ZBX_SERVER_HOST: zabbix-server
      PHP_TZ: "Asia/Kolkata" # Adjust this for your timezone
    depends_on:
      - zabbix-server
    ports:
      - "8080:8080"
    networks:
      - zabbix-network
    restart: unless-stopped

  zabbix-agent:
    image: zabbix/zabbix-agent:latest
    container_name: zabbix-agent
    environment:
      ZBX_SERVER_HOST: zabbix-server
    depends_on:
      - zabbix-server
    networks:
      - zabbix-network
    restart: unless-stopped

volumes:
  zabbix-db-data:
  zabbix-server-data:

networks:
  zabbix-network:
    driver: bridge
