---
- name: Check if the secret.psk exists
  stat:
    path: /etc/zabbix/secret.psk
  register: psk_file

- name: Generate a random PSK and save to secret.psk
  shell: "openssl rand -hex 64 > /etc/zabbix/secret.psk"
  when: not psk_file.stat.exists

- name: Register secret.psk
  slurp:
    src: /etc/zabbix/secret.psk
  register: secret_psk

- name: Set proper permissions for the secret.psk file
  file:
    path: /etc/zabbix/secret.psk
    owner: zabbix
    group: zabbix
    mode: '0600'
