---
- name: Install Zabbix Agent Repo
  apt:
    deb: https://repo.zabbix.com/zabbix/{{ zabbix_agent_version }}/release/{{ ansible_distribution | lower }}/pool/main/z/zabbix-release/zabbix-release_latest_{{ zabbix_agent_version }}+{{ ansible_distribution | lower }}{{ ansible_distribution_version }}_all.deb

- name: Install Zabbix Agent
  apt:
    update_cache: yes
    name: zabbix-agent

- name: Copy zabbix agent config file to host
  template:
    src: zabbix_agentd.conf.j2
    dest: /etc/zabbix/zabbix_agentd.conf
